steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-website', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-website']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'my-website',
        '--image',
        'gcr.io/$PROJECT_ID/my-website',
        '--platform',
        'managed',
        '--region',
        'eu-west9',
        '--quiet'
      ]
images:
  - 'gcr.io/$PROJECT_ID/my-website'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET